------------------ SPU 1: HACK.SPUSOLRPRACTICE --------------------
--- CAN BE ADDED IN TABLE CREATION IN THE COLUMN
--HACK 1: Nullify the SPONSORSHIPXML column for practices with client contracts set to start in the future
UPDATE SHOW.SOLR_PRACTICE
SET SPONSORSHIP_XML = NULL
WHERE PRACTICE_ID IN (
    SELECT SP.PRACTICE_ID
    FROM SHOW.SOLR_PRACTICE SP
    JOIN MID.PRACTICE_SPONSORSHIP PS ON PS.PRACTICE_ID = SP.PRACTICE_ID
    JOIN BASE.CLIENT C ON PS.CLIENT_CODE = C.CLIENT_CODE
    JOIN SHOW.CLIENT_CONTRACT CC ON C.CLIENT_ID = CC.CLIENT_ID
    WHERE CC.CONTRACT_START_DATE > GETDATE() );

--- CAN BE ADDED IN TABLE CREATION IN THE COLUMN
-- HACK 2: Nullify the SPONSORSHIPXML column for practices with client contracts set to end in the past
UPDATE SHOW.SOLR_PRACTICE
SET LEGACY_KEY_PRACTICE = CONCAT('HGPPZ', SUBSTRING(REPLACE(PRACTICEID,'-',''), 1, 16))
WHERE LEGACY_KEY_PRACTICE IS NULL;



----------------- SPU 2: SHOW.SPUREMOVEPRACTICEWITHNOPROVIDER ---------------------
-- CAN BE ADDED IN TABLE CREATION AS A DELETE STATEMENT AT THE END
-- Remove practices with no providers
DELETE FROM SHOW.SOLR_PRACTICE
WHERE NOT EXISTS (
    SELECT 1
    FROM BASE.PROVIDER_TO_OFFICE AS A 
    JOIN BASE.OFFICE AS B ON B.OFFICE_ID = A.OFFICE_ID
    JOIN BASE.PRACTICE AS C ON C.PRACTICE_ID = B.PRACTICE_ID
    JOIN SHOW.SOLR_PROVIDER D ON A.PROVIDER_ID = D.PROVIDER_ID
    WHERE SHOW.SOLR_PRACTICE.PRACTICE_ID = C.PRACTICE_ID
);


